<?php
defined('BASEPATH') OR exit('No direct script access allowed');
include(APPPATH.'config/routes_admin.php');
include(APPPATH.'config/routes_api.php');
include(APPPATH.'config/routes_newapi.php');
$route['translate_uri_dashes'] = FALSE;
$route['default_controller'] = 'home/login';
$route['loginchk'] = 'Authenticate/login';
$route['signup'] = 'Home/signup';
$route['register'] = 'Authenticate/register';
$route['forgot-password'] = 'Home/forgot_password';
$route['streams'] = 'Home/streams';
$route['our-success-story'] = 'Home/browseSuccessStories';
$route['courses/(:any)'] = 'Home/coursesByStream/$1';
$route['about-course/(:any)'] = 'Home/aboutCourse/$1';
$route['about-us'] = 'Home/aboutUs';
$route['contact-us'] = 'Home/contactUs';
$route['post-enquiry'] = 'Enquiry/submitEnquiry';
$route['all-colleges'] = 'Home/allColleges';
$route['college-info/(:any)/(:any)'] = 'Home/collegeInfo/$1/$2';
$route['college-detail/(:any)/(:any)/(:any)'] = 'Home/collegeDetail/$1/$2/$3';
$route['terms-condition'] = 'Home/termsConditions';
$route['privacy-policy'] = 'Home/privacyPolicy';
$route['news'] = 'Home/news';
$route['news-detail/(:any)/(:any)'] = 'Home/newsDetail/$1/$2';
$route['edit-profile'] = 'Authenticate/EditUserProfile';
$route['profile'] = 'Authenticate/userProfile';
$route['search'] = 'Home/searchPage';
$route['payments'] = 'Home/paymentList';
$route['search-content'] = 'Home/searchContent';
$route['update-profile'] = 'ExamController/updateUserProfile';
$route['get-exam-courses'] = 'ExamController/getExamCourses';
$route['get-sub-category'] = 'ExamController/getSubCategory';
$route['get-domicile-sub-category'] = 'ExamController/getDomicileSubCategory';
$route['states/(:any)'] = 'Home/stateList/$1';
$route['state-wise-colleges/(:any)/(:any)'] = 'Home/state_wise_colleges/$1/$2';
$route['course-details/(:any)/(:any)'] = 'Home/selectedCourse/$1/$2';
$route['send-otp'] = 'Authenticate/forgot_password';
$route['update-password'] = 'Authenticate/requestToResetPassword';
$route['verify-otp/(:any)'] = 'Authenticate/verify_otp/$1';
$route['reset-password/(:any)'] = 'Authenticate/reset_password/$1';
$route['otp-verification'] = 'Authenticate/OtpVerification';
$route['otp-verification'] = 'Authenticate/OtpVerification';
$route['resend-otp'] = 'Authenticate/resend_otp';
$route['verify-done'] = 'Authenticate/verify_done';
$route['filter-college'] = 'Home/filterCollegeData';
$route['plan'] = 'Home/plan';
$route['college-predictor'] = 'Home/collegePredictor';
$route['get-domicile-main-category'] = 'ExamController/getDomicileMainCategories';
$route['logout'] = 'Authenticate/logout';
$route['payment/pay-success'] = 'Payment/successPayment';
$route['small/about-us'] = 'SmallScreen/Home/about_us';
$route['testimonials'] = 'Home/testimonials';
$route['testimonial-explore'] = 'Home/testimonials_explore';
$route['small/home'] = 'SmallScreen/Home/splash_screen';
$route['large/home'] = 'Home/index';
$route['user/logout'] = 'SmallScreen/Authenticate/logout';

